# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.Tree')),
            ],
        ),
    ]
